language: node_js
node_js:
  - 'node'
cache:
  yarn: true
deploy:
    # Staging environment
  - provider: s3
    bucket: $STAGING_BUCKET_NAME
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    local_dir: build
    upload-dir: current/app
    region: $AWS_DEFAULT_REGION
    on:
      branch: master

    # Prepare production deployment
  - provider: s3
    bucket: $STAGING_BUCKET_NAME
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    access_key_id: $AWS_ACCESS_KEY_ID
    skip_cleanup: true
    local_dir: build
    upload-dir: releases/$TRAVIS_TAG
    region: $AWS_DEFAULT_REGION
    on:
      tags: true
  - provider: script
    script: ./config/travis/prepare_production_deployment.sh
    on:
      tags: true